### ISSUE TITLE
How Can I Run it on >= iOS8......great thanks

### ISSUE THREAD

**Issue by zeku2022** [PerfectFreeze/PFWebViewController#19]
now it must >= ios 9.0 ...

**Comment by Cee** [comment]
@xiaoxiongke We'll not support iOS 8.0 because `UIStackView` was introduced in iOS 9. If you'd like to pack it into your project, use [FDStackView](https://github.com/forkingdog/FDStackView) as an alias or rewrite the toolbar.

**Comment by zeku2022** [comment]
Thank you very much! :)
